<?php

use Illuminate\Database\Seeder;

class ConectorsTableSeeder extends Illuminate\Database\Seeder {
	
	public function run(){
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'alguna'			
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'algunas'			
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'algun'			
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'algunos'			
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'aplicaciòn'			
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'aplicación'			
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'aplicacion'			
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'asi'			
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'asì'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'así'
			)
		);		
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'aunque'			
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'bien'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'cada'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'cambio'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'cual'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'cuanto'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'cuesta'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'con'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'cuando'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'conocer'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'contrario'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'como'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'compra'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'comprar'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'comprarjuntos'
			)
		);		
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'cosa'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'coso'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'costo'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'busco'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'buscar'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'buscando'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'buscaba'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'dado'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'del'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'donde'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'dicho'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'despues'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'embargo'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'esta'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'està'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'està'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'está'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'estos'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'estoy'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'este'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'estè'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'esté'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'existe'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'finalmente'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'juntos'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'hay'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'hacer'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'lado'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'lista'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'listar'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'listeme'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'las'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'los'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'mas'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'màs'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'más'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'mejor'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'menos'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'medio'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'muestre'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'muestreme'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'obstante'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'oferte'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'ofertar'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'otro'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'otros'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'otra'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'otras'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'para'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'producto'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'proveedor'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'puede'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'que'
			)
		);	
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'quiero'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'quien'
			)
		);		
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'sin'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'sino'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'solo'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'sola'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'solamente'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'siempre'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'servicio'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'saber'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'tambien'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'tienda'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'tendero'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'una'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'uno'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'unas'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'unos'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'ver'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'vende'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'venda'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'vender'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'venderme'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'select'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'where'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'from'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'left'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'join'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'and'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'or'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'order'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'right'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'delete'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'create'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'insert'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'update'
			)
		);
		\DB::table('seg_conectors')->insert(array(
			'conector'=>'drop'
			)
		);
	}
}
