<?php

use Illuminate\Database\Seeder;

class PermitTableSeeder extends Illuminate\Database\Seeder {
	
	public function run(){
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>1			
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>2			
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>4
			)
		);\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>5			
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>6			
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>5
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>1
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>3
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>4
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>5
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>5
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>6
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>5
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>6
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>4
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>5
			)
		);
		
		//PERMISOS DE TENDERO
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>8,
			'option_id'=>12
			)
		);		
						
	}
	
}
